import { Videotape } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Nav from "./nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Render the application's root HTML shell with header, main content area, and footer.
 *
 * The header contains the brand link and navigation; the main area hosts `children`; global font variables and base layout styles are applied to the document.
 *
 * @param children - React nodes to be rendered inside the main content area
 * @returns The top-level HTML element that wraps the application's layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen flex-col justify-center">
          <header className="flex justify-between border-b-1 px-2">
            <Link
              href={"/"}
              className="flex items-center font-semibold text-3xl tracking-tight"
            >
              <Videotape color="#ff0000" size={28} /> Stube
            </Link>
            <Nav />
          </header>
          <main className="flex-1 overflow-auto">{children}</main>
          <footer className="text-center">&#169; seonu 2025</footer>
        </div>
      </body>
    </html>
  );
}